# Generated by Django 4.2.7 on 2025-09-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
